services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    container_name: whale-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=whale
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: whale-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
  redis:
    container_name: whale-redis-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ~/apps/redis:/var/lib/redis/data
