services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    container_name: whale-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=whale
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: whale-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
  redis:
    container_name: whale-redis-cache
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ~/apps/redis:/var/lib/redis/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: whale-search
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=search
      - cluster.name=whale-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .~/apps/search:/var/lib/search/data
    ports:
      - '9200:9200'
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: whale-kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
